### PR TITLE
[Future] Tracking 1.16 changes 

### PR DESCRIPTION
**Pull request by Xernium**
This Pull-request is meant to be merge-ready when 1.16 gets released so a usable Bungeecord can be obtained ASAP. The changes in this PR will get lost when Bungeecord gets updated to support 1.16, that is intentional. This is just meant to maybe make @electronicboy s life a little easier ;)

### CODE REVIEW

**Comment by TheCompieter** [comment]
Thank you very much for this cause now i can have 1.16 snapshot support with vanillacord hope it works

**Comment by TheCompieter** [comment]
Confimation it works with vanillacord and viaversion thanks you very much @Xernium

**Comment by Xernium** [comment]
I should mention that for now you can find builds of this fork at https://jenkins.krusic22.com/job/Travertine-Xernium/ (kindly provided by @krusic22)

**Comment by Xernium** [comment]
I should add that I'm only tracking *all* snapshots so far because of accuracy reasons. The unused or obsolete ones can be flattened out rather easily and I will do so before release

**Comment by tsao-chi** [comment]
This won't make @electronicboy s life a little easier, but this maybe make @md-5 s life a little easier

**Comment by Xernium** [comment]
@tsao-chi I doubt it; last time @electronicboy hacked together a working bungeecord well ahead of time md-5 was ready with it on his side

**Comment by Xernium** [comment]
That said; I am open to it. I’ll PR my changes th BungeeCord and see what he has to say;

**Comment by astei** [comment]
@Xernium You'll get the cold shoulder, with him saying that "updates are handled internally" and your PR will be closed. I didn't need to open a PR to demonstrate this - there are several examples of this.

**Comment by Xernium** [comment]
@astei I wasn’t gonna PR to experience that, I know very well what the outcome would be sadly

**Comment by Xernium** [comment]
That said who cares in the end- I’ll open my PR and get shut down. I knew that that’s gonna happen from the moment I sent that message. But at least I tried them

**Comment by Xernium** [comment]
Update: Well I got my answer in IRC and I’ll leave it at that. I won’t attempt to contribute to bungeecord directly again. But oh well at least I showed good faith ¯\_(ツ)_/¯

**Comment by krusic22** [comment]
You could move the PR to Travertine, as that got 1.15 support before upstream.

**Comment by astei** [comment]
...this is literally a Travertine PR.

**Comment by krusic22** [comment]
Thanks for reminding me.

**Comment by aikar** [comment]
I would rather be PR'd to Waterfall. Not all of us use Travertine.

Then Travertine will get it from WF.

**Comment by TychoWerner** [comment]
Does this need changes when 20w18a comes out or whatever version for that matter or will the previous version still work?

**Comment by Xernium** [comment]
@TychoWerner Since the snapshots are a highly dynamic element; Yes of course it will change. That’s what this pull request is for. If someone had to do one thing to make all future snapshots work then we wouldn’t be here atm. We can’t exactly predict what Mojang will do to that level. So yes there are gonna be updates and yes stuff is going to break (most likely)

**Comment by Xernium** [comment]
Side note; I will move this to Waterfall during the coming weekend as per @aikar s suggestion

**Comment by JRoy** [comment]
@aikar Waterfall has never supported pre-release protocols. The pre-release protocols have always been done in Travertine (dbe27f380f23a37386615e317cc1e5a78a65e636, 32c100ed0360addab7421554ee81c86a018e27e1, ac8e757b85208996874605ed305cfdad12d6c3fd). @Xernium for that reason I say keep this here unless aikar or some other member of the paper team replies.

**Comment by Xernium** [comment]
@JRoy It’d help if you scrolled up in the conversation a bit ;)

**Comment by TychoWerner** [comment]
> @TychoWerner Since the snapshots are a highly dynamic element; Yes of course it will change. That’s what this pull request is for. If someone had to do one thing to make all future snapshots work then we wouldn’t be here atm. We can’t exactly predict what Mojang will do to that level. So yes there are gonna be updates and yes stuff is going to break (most likely)

Thanks for your reply. I was looking at your latest commit (https://github.com/PaperMC/Travertine/pull/120/commits/6af17c8eb97a99cd51d7262c2ed78345a4f17f10) and it seemed "just" adding 20w17a on certain points which to my eyes seems to be easily be planned ahead (and even looked like it already did with FUTURE_SNAPSHOT).

Do a lot of changes have to be made to support the newer versions, I understand that changes have to be made when things to players, chat, and other server things change.

But new blocks and a couple of of new mobs they don't have affect as it has nothing to do with Bungeecord right? Or am I seeing that wrong?

Thanks for making this available, it helps me bring together multiple versions of servers with also snapshots. We play a survival world and can now easily get to a creative testing world 👍

**Comment by TheCompieter** [comment]
@Xernium i got an issue with players being disconnected and it says that they where sent too an fallback server while the serverthey were on didn't go down i am using the last buid as of this moment and have viaversion on my proxy along with someother plugins that shoudn't affect this. hope you can help with this. it's only with 1.16

**Comment by TheCompieter** [comment]
am atm looking if this is an 1.16 viaversion issue by moving them too the servers intead of the proxy itself cause had more problems with viaversion though it shoudn't interfere with this

**Comment by Xernium** [comment]
@TheCompieter I don’t test with ViaVersion especially since it wasn’t updated yet when I pushed this update. It worked on a vanilla snapshot server. I’ll investigate into it.

**Comment by TheCompieter** [comment]
thanks if you need any more specific information say so.

**Comment by TheCompieter** [comment]
also when throwing out an fishing line it doesn't show the line or dobber but does in single player and this is without viaversion and with viaversion.

**Comment by Xernium** [comment]
@TheCompieter The fishing issue might be due to an entity rewriter being broken. I'll have to look at it. Also I can't reproduce your issue. I tried it with a network that has a 1.15.2 paper server with ViaVersion and a Vanillacord 20w17a server. Is there a specific trigger to the issue?

**Comment by Xernium** [comment]
Side note; a productive conversation here using comments isn't going to be easy. If you use Discord please @ me on the ViaVersion or on the PaperMC Discord server, that could speed this up a lot

**Comment by TheCompieter** [comment]
> 
> 
> @TheCompieter The fishing issue might be due to an entity rewriter being broken. I'll have to look at it. Also I can't reproduce your issue. I tried it with a network that has a 1.15.2 paper server with ViaVersion and a Vanillacord 20w17a server. Is there a specific trigger to the issue?

No it's random and no error as far as i know i am now just using it without viaversion and if it still happens i will let you know.

> 
> 
> Side note; a productive conversation here using comments isn't going to be easy. If you use Discord please `@Five#0001` me on the ViaVersion or on the PaperMC Discord server, that could speed this up a lot

Okay i will do that

**Comment by Xernium** [comment]
Branch will be reworked in favour of https://github.com/PaperMC/Waterfall/pull/494

**Pull request closed without merging**
